import type { BrandCatalog, BrandTheme } from '../../lib/brandCatalog'
import { typeStyle, length } from '../../lib/brandCatalog'
import { brandIdentifier, resolveBrandFont } from '../../lib/brandPresentation'
import { componentGroups, componentSize } from '../../lib/brandExperience'
import { BrandComponentSample } from './BrandComponentSample'
import { BrandAppliedPreview } from './BrandAppliedPreview'

export const experienceSections=[{id:'overview',label:'Overview'},{id:'dna',label:'Design DNA'},{id:'library',label:'Component Library'},{id:'applied',label:'Applied Canvas'},{id:'resources',label:'Resources'}]
export function BrandExperienceCatalog({catalog,theme}:{catalog:BrandCatalog;theme:BrandTheme}) {
 const asset=brandIdentifier(catalog.entry.slug,catalog.spec)
 const palette=[['Primary',catalog.spec.colors.primary],['Surface',theme.colors.surface],['Canvas',theme.colors.canvas],['Text',theme.colors.text],['Muted',theme.colors.muted],['Border',theme.colors.border==='transparent'?undefined:theme.colors.border],['Accent',catalog.colors.find(([key])=>/^accent/.test(key))?.[1]]]
 const typography=[['Display',/display|hero/],['Heading',/heading|headline|title|display-md|lead/],['Body',/body|paragraph/],['Caption',/caption|small|label/]] as const
 return <div className="bc-content bc-experience" data-catalog-mode="curated">
  <section className="bc-section ex-overview" data-section="overview"><small>01 / Overview</small><h3>{catalog.entry.name}</h3><p>색과 글자의 인상부터 화면에 적용된 조합까지 살펴보세요.</p><div className="bc-dna">{catalog.dna.map(d=><span key={d.label} title={d.evidence}>{d.label}</span>)}</div><p className="bc-note">DESIGN.md 기반 DRH 예시 · 공식 제품 화면이 아닙니다.</p></section>
  <section className="bc-section" data-section="dna"><h4>Design DNA</h4><h5>Semantic palette</h5><div className="ex-palette">{palette.map(([label,value])=><div key={label}><i style={{background:value||'transparent'}}/><b>{label}</b><code>{value||'원본 미지정'}</code></div>)}</div><details className="bc-evidence"><summary>Evidence · Color</summary><p>source · DESIGN.md colors / 명시된 테마 우선. Surface·Canvas·Text·Muted·Border는 기존 theme resolver의 표시 역할입니다.</p>{catalog.colors.map(([key,value])=><p key={key}>{key} · {value}</p>)}<p>confidence · 원본 선언값과 표시 역할 매핑. Accent 미지정 시 임의로 보완하지 않습니다.</p></details>
   <div className="ex-type-hierarchy">{typography.map(([label,pattern],i)=>{const found=(label==='Body'?catalog.roles.find(([key])=>key==='body'):undefined)||catalog.roles.find(([key])=>pattern.test(key));const role=found?.[1];const font=resolveBrandFont(role?{...role,...(i>0?{script:'ko' as const}:{})}:{});return <div key={label}><small>{label}</small>{role?<><p style={{...typeStyle(role),fontFamily:font.stack,fontSize:`clamp(12px, ${length(role.fontSize)||[48,32,17,13][i]+'px'}, ${[48,32,20,14][i]}px)`}}>{['Design speaks.','더 명확한 일상의 디자인','색과 글자, 여백이 모여 브랜드의 목소리가 됩니다.','작은 디테일까지 이어지는 경험 · Aa 0123'][i]}</p><small className="bc-note">{font.family}{font.scriptFallback?' · 한글 대체: '+font.scriptFallback:''} · {font.kind==='proprietary'?'원본 전용 글꼴 대체 표시':font.kind}</small><details className="bc-evidence"><summary>Evidence · {label}</summary><p>source · typography.{found?.[0]} / confidence · 원본 선언값</p><p>표시 크기는 비교용 계층입니다. original value:</p>{Object.entries(role).map(([key,value])=><p key={key}>{key} · {String(value)}</p>)}</details></>:<p className="bc-note">원본에 이 역할이 지정되지 않았습니다.</p>}</div>})}</div>
  </section>
  <section className="bc-section" data-section="library"><h4>Component Library</h4><p className="bc-note">원본 구성요소의 대표 예시 · 전체 변형과 기술 근거는 전체 카탈로그에서 확인하세요.</p>{componentGroups.map(group=>{const selected=group.kinds.flatMap(kind=>catalog.components.filter(c=>c.kind===kind&&!/hover|pressed|focus|disabled|selected|active/.test(c.key)).slice(0,kind==='buttons'?3:2));return selected.length?<section className="ex-group" key={group.label}><h5>{group.label}</h5><div className="ex-component-grid">{selected.map(c=><div className={'ex-size-'+componentSize(c.kind)} key={c.key}><BrandComponentSample component={c} catalog={catalog} theme={theme}/></div>)}</div></section>:null})}</section>
  <section className="bc-section" data-section="applied"><h4>Applied Canvas</h4><BrandAppliedPreview catalog={catalog} theme={theme}/></section>
  <section className="bc-section" data-section="resources"><h4>Resources</h4>{asset.attribution&&<p className="bc-note">{asset.attribution} <a href={asset.evidenceUrl} target="_blank" rel="noreferrer">로고 사용 조건 ↗</a></p>}<div className="bc-resources">{catalog.officialResources.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer"><small>{r.type}</small><b>{r.label} ↗</b><span>{r.description}</span></a>)}</div>{!catalog.officialResources.length&&<p className="bc-note">검증된 공식 자료 링크가 등록되지 않았습니다.</p>}<p className="bc-note">{catalog.entry.sourceName||'VoltAgent / awesome-design-md'} · {catalog.entry.upstreamCommit.slice(0,12)}<br/>문서 라이선스와 브랜드 상표·로고·폰트 권리는 별도입니다. {catalog.entry.referenceRights}</p><a href={import.meta.env.BASE_URL+'vendor/'+(catalog.entry.vendorSource||'awesome-design-md')+'/'+catalog.entry.slug+'/DESIGN.md'}>원본 DESIGN.md ↗</a></section>
 </div>
}
