import { lazy, Suspense, Fragment, type CSSProperties } from 'react'
import { componentStyle, length, scalar, typeStyle, type BrandCatalog as Catalog, type BrandTheme } from '../../lib/brandCatalog'
import { brandIdentifier, cleanSource, curatedColors, curatedRoles, curatedRule, representativeRows, motionEvidence, resolveBrandFont, responsiveEvidence, shortRule, sourceLines, sourceTable } from '../../lib/brandPresentation'
import { BrandComponentSample } from './BrandComponentSample'
const BrandSourceNotes=lazy(()=>import('./BrandSourceNotes'))
const resourceLabels:Record<string,string>={'brand-guidelines':'브랜드 가이드','design-system':'디자인 시스템','developer-design-guide':'개발자 디자인 가이드',typography:'타이포그래피',components:'컴포넌트',assets:'브랜드 에셋',other:'공식 자료'}
export function catalogStyle(theme:BrandTheme):CSSProperties{return {'--bc-canvas':theme.colors.canvas,'--bc-surface':theme.colors.surface,'--bc-ink':theme.colors.text,'--bc-muted':theme.colors.muted,'--bc-border':theme.colors.border} as CSSProperties}
function Evidence({value}:{value:unknown}) {return sourceLines(value).length?<details className="bc-raw"><summary>원문 근거 보기</summary><Suspense fallback={<p className="bc-note">원문을 불러오는 중…</p>}><BrandSourceNotes value={value}/></Suspense></details>:null}
function RuleCards({value,expanded,kind,slug}:{value:unknown;expanded:boolean;kind:'elevation'|'responsive';slug:string}) {
 const rows=sourceTable(value)
 const lines=sourceLines(value).filter(s=>!/^\||^#/.test(s)).map(cleanSource)
 return <><div className="bc-grid bc-rules">{rows.length?(expanded?rows:representativeRows(rows,6)).map((row,i)=>{const summary=curatedRule(slug,kind,row);return <article key={i}><small>{kind==='elevation'?'단계':'화면 조건'}</small><h5>{row[0]}</h5>{kind==='responsive'&&<strong className="bc-breakpoint">{row[1]}</strong>}{summary?<p>{summary}</p>:<><p>{kind==='elevation'?shortRule(row[1]||''):shortRule(row[2]||'')}</p>{kind==='elevation'&&row[2]&&<p className="bc-note">사용처 · {shortRule(row[2])}</p>}</>}</article>}):<p className="bc-note">{lines.length?shortRule(lines[0].split(/(?<=\.)\s/)[0]):'정성적 규칙이 정의되어 있습니다. 원문 근거를 확인하세요.'}</p>}</div>{!expanded&&rows.length>6&&<p className="bc-note bc-catalog-count">대표 6개 / 전체 {rows.length}개 · 크게 보기에서 모든 조건을 확인하세요.</p>}<Evidence value={value}/></>
}
export function BrandCatalog({catalog,theme,expanded=false}:{catalog:Catalog;theme:BrandTheme;expanded?:boolean}){
 const {spec,entry}=catalog
 const asset=brandIdentifier(entry.slug,spec)
 const roles=expanded?catalog.roles:curatedRoles(catalog.roles)
 const colors=expanded?catalog.colors:curatedColors(catalog.colors)
 const motion=motionEvidence(spec)
 const sections=catalog.sections.filter(s=>expanded||s.kind!=='other')
 const more=(shown:number,total:number)=>!expanded&&total>shown?<p className="bc-note bc-catalog-count">대표 {shown}개 / 전체 {total}개 · 전체 카탈로그는 ‘크게 보기’에서 확인하세요.</p>:null
 return <div className="bc-content" data-catalog-mode={expanded?'full':'curated'}>
  <p className="bc-note">{expanded?'전체 카탈로그 · 모든 정의와 원문 근거':'핵심 보기 · 브랜드를 비교하는 대표 스타일'}<br/>DESIGN.md 기반 DRH 예시입니다. 공식 제품 화면이 아닙니다.</p>
  {asset.attribution&&<p className="bc-note bc-attribution">{asset.attribution} <a href={asset.evidenceUrl} target="_blank" rel="noreferrer">로고 사용 조건 ↗</a></p>}
  {sections.map(section=><section key={section.id} data-section={section.id} className={'bc-section bc-section-'+section.type}>
   <h4>{section.label}{expanded&&section.count!==undefined&&<small>{section.count}</small>}</h4>
   {section.type==='official-resources'&&<div className="bc-resources">{catalog.officialResources.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer" title={r.description}><small>{resourceLabels[r.type]}</small><b>{r.label} ↗</b><span>{r.description}</span></a>)}</div>}
   {section.type==='overview'&&<><div className="bc-dna">{catalog.dna.map(d=><span key={d.label} title={d.evidence}>{d.label}</span>)}</div><div className="bc-overview-samples"><div className="bc-type-scroll"><span style={{...typeStyle(catalog.roles.find(([k])=>/heading|headline|title/.test(k))?.[1]||catalog.roles[0]?.[1]||{}),fontSize:'clamp(24px,3vw,40px)'}}>Aa — Design</span></div>{catalog.components.find(c=>c.kind==='buttons')&&<span className="bc-overview-button" style={componentStyle(catalog.components.find(c=>c.kind==='buttons')!.values,catalog,theme)}>Continue →</span>}</div></>}
   {section.type==='colors'&&<><div className="bc-grid bc-colors">{colors.map(([key,value])=><div key={key} className="bc-color"><i style={{background:value}}/><span>{key}<code>{value}</code></span></div>)}</div>{more(colors.length,catalog.colors.length)}</>}
   {section.type==='typography'&&<><div className="bc-type-list">{roles.map(([key,role])=>{const font=resolveBrandFont(role);return <div key={key} className="bc-type" data-font-kind={font.kind}><h5>{key}</h5><small>크기 {scalar(role.fontSize,'미지정')} · 굵기 {scalar(role.fontWeight,'미지정')} · 행간 {scalar(role.lineHeight,'기본')} · 자간 {scalar(role.letterSpacing,'기본')}</small><div className="bc-type-scroll"><span className={/body|paragraph|caption|small|label/.test(key)?'bc-type-readable':undefined} style={{...typeStyle(role),fontSize:expanded?length(role.fontSize):'clamp(12px, '+(length(role.fontSize)||'16px')+', 48px)','--bc-role-size':length(role.fontSize)||'16px'} as CSSProperties}>{/mono/.test(key)?'const design = 2026;':/body|paragraph/.test(key)?'Good design makes the everyday feel simple.':/caption|small|label/.test(key)?'Details that make a difference':'Aa — Design'}</span></div><small>원본 지정: {font.declared||'미지정'}<br/>표시 글꼴: {font.family} · {font.kind==='open-font'?'로컬 공개 폰트':font.kind==='system-font'?'OS 글꼴 · 환경에 따라 대체':'대체 글꼴'}</small></div>})}</div>{more(roles.length,catalog.roles.length)}</>}
   {section.type==='components'&&(()=>{const all=catalog.components.filter(c=>c.kind===section.kind);const selected=expanded?all:[...all.filter(c=>!/hover|pressed|focus|disabled|selected/.test(c.key)),...all.filter(c=>/hover|pressed|focus|disabled|selected/.test(c.key))].slice(0,section.kind==='buttons'?3:2);return <><div className="bc-grid">{selected.map(c=><BrandComponentSample key={c.key} component={c} catalog={catalog} theme={theme}/>)}</div>{more(selected.length,all.length)}</>})()}
   {section.type==='geometry'&&<div className="bc-grid">{[spec.spacing,spec.radius].map((scale,i)=>Object.keys(scale).length>0&&<div key={i}><h5>{i?'Radius · 모서리':'Spacing · 간격'}</h5>{(expanded?Object.entries(scale):Object.entries(scale).slice(0,8)).map(([key,value])=><div className="bc-scale" key={key}><i style={i?{width:36,height:36,borderRadius:length(value)}:{width:`min(${length(value)}, 240px)`,height:8}}/><code>{key}: {value}</code></div>)}{more(Math.min(Object.keys(scale).length,8),Object.keys(scale).length)}</div>)}</div>}
   {section.type==='elevation'&&<><RuleCards slug={entry.slug} value={sourceLines(spec.depth).length?spec.depth:spec.border} expanded={expanded} kind="elevation"/>{expanded&&<><Evidence value={spec.border}/><div className="bc-grid bc-depth-samples">{catalog.components.filter(c=>c.values.border||c.values.boxShadow||c.values.shadow).map(c=><div key={c.key}><h5>{c.key}</h5><div className="bc-depth" style={{...componentStyle(c.values,catalog,theme),padding:16,height:80,fontSize:12}}>경계와 깊이</div></div>)}</div></>}</>}
   {section.type==='responsive'&&<RuleCards slug={entry.slug} value={responsiveEvidence(spec)} expanded={expanded} kind="responsive"/>}
   {section.type==='motion'&&<>{motion.state==='not-in-scope'?<p className="bc-note">이 DESIGN.md에서는 별도의 모션 규칙을 정의하지 않습니다.</p>:<ul className="bc-rule-list">{(expanded?motion.lines:motion.lines.slice(0,3)).map((s,i)=><li key={i}>{shortRule(s)}</li>)}</ul>}<Evidence value={motion.raw}/></>}
   {section.type==='layout'&&<><div className="bc-layout" data-layout={spec.layout} aria-label={spec.layout+' layout schematic'}>{['탐색','주요 영역','보조 콘텐츠','보조 콘텐츠'].map((v,i)=><div key={i}>{v}</div>)}</div><p className="bc-note">{spec.layout} · 원본 특성을 요약한 구성도</p>{expanded&&<Evidence value={spec.traits}/>}</>}
   {section.type==='source'&&<><p className="bc-note">VoltAgent / awesome-design-md · MIT · {entry.upstreamCommit.slice(0,12)}<br/>공식 리소스 링크와 별개인 DESIGN.md 수집 출처입니다.</p><a href={import.meta.env.BASE_URL+'vendor/awesome-design-md/'+entry.slug+'/DESIGN.md'} target="_blank" rel="noreferrer">원본 DESIGN.md ↗</a>{expanded&&<><a className="bc-full-json" href={import.meta.env.BASE_URL+'brand-design-specs/'+entry.slug+'.json'} target="_blank" rel="noreferrer">전체 Spec JSON ↗</a><details><summary>전체 원문 섹션 · 개발자 근거</summary>{Object.entries(spec.sections||{}).map(([k,v])=><Fragment key={k}><h5>{k}</h5><pre>{v}</pre></Fragment>)}</details></>}</>}
  </section>)}
 </div>
}
