import { ExternalLink, Github, Search, ShieldCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { sourceMap, sourceStats } from '../data/sourceMap'

export function SourcesPage(){
  const [query,setQuery]=useState(''); const [status,setStatus]=useState('All')
  const rows=useMemo(()=>sourceMap.filter(s=>{if(status!=='All'&&s.recommendation!==status)return false;if(query){const q=query.toLowerCase();return [s.source,s.category,s.what_it_provides,s.stack,s.license].join(' ').toLowerCase().includes(q)}return true}),[query,status])
  return <main className="sources-page"><section className="listing-hero sources-hero"><span className="eyebrow">SOURCE MAP / REVIEWED 2026-09-06</span><h1>Beautiful is not<br/><i>a license.</i></h1><p>The source index keeps provenance visible. Code, screenshots, images, fonts, icons and brand assets can carry different rights — so every import decision is explicit.</p><div className="source-stats"><div><b>{sourceStats.count}</b><span>candidate sources</span></div><div><b>{sourceStats.statusCounts['🟢']}</b><span>copy candidates</span></div><div><b>{sourceStats.statusCounts['🟡']}</b><span>reference only</span></div><div><b>{sourceStats.statusCounts['🔴']}</b><span>restricted</span></div></div></section>
    <section className="sources-table-wrap"><div className="sources-tools"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search source, stack, license…"/></label><div>{['All','🟢','🟡','🔴'].map(x=><button key={x} className={status===x?'active':''} onClick={()=>setStatus(x)}>{x==='All'?'All':x}</button>)}</div></div><div className="sources-table"><div className="source-row header"><span>Source</span><span>Category / Stack</span><span>License</span><span>Decision</span></div>{rows.map(s=><div className="source-row" key={s.source}><div><b>{s.source}</b><p>{s.what_it_provides}</p><div className="source-links"><a href={s.url} target="_blank" rel="noreferrer">Original <ExternalLink size={13}/></a>{s.github&&<a href={s.github} target="_blank" rel="noreferrer"><Github size={13}/> GitHub</a>}</div></div><div><span>{s.category}</span><small>{s.stack}</small></div><div><b>{s.license}</b><small>{s.redistribution}</small></div><div><span className={`source-status s-${s.recommendation}`}>{s.recommendation}</span><small>{s.caveat||s.attribution}</small></div></div>)}</div></section>
  </main>
}
