import { ExternalLink, Github, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { sourceMap, sourceStats } from '../data/sourceMap'

const safe=(url?:string)=>Boolean(url && /^https?:\/\//.test(url))

export function SourcesPage(){
  const [query,setQuery]=useState(''); const [status,setStatus]=useState('All')
  const rows=useMemo(()=>sourceMap.filter(s=>{if(status!=='All'&&s.recommendation!==status)return false;if(query){const q=query.toLowerCase();return [s.source,s.category,s.what_it_provides,s.stack,s.license].join(' ').toLowerCase().includes(q)}return true}),[query,status])
  return <main className="sources-page"><section className="listing-hero sources-hero"><span className="eyebrow">SOURCE MAP / REVIEWED 2026-09-08</span><h1>더 예쁘고 더 빨라서<br/><i>복사 가능한 것만 남깁니다.</i></h1><p>Code, Screenshot, Image, Font, Icon등 Brand Asset의 권리에서 자유로운 것만 모았습니다. Hub는 Source를 License 판단과 숨기지 않고 함께 보여줍니다.</p><div className="source-stats"><div><b>{sourceStats.count}</b><span>전체 Source</span></div><div><b>{sourceStats.statusCounts['IMPORT / COPY CANDIDATE']}</b><span>가져오기 가능</span></div><div><b>{sourceStats.statusCounts['REFERENCE']}</b><span>참고 전용</span></div><div><b>{sourceStats.statusCounts['RESTRICTED']}</b><span>제한</span></div></div></section>
    <section className="sources-table-wrap"><div className="sources-tools"><label><Search size={17}/><input aria-label="출처 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Source, Stack, License 검색"/></label><div>{['All','IMPORT / COPY CANDIDATE','REFERENCE','RESTRICTED'].map(x=><button aria-label={x==='All'?'전체 출처':x==='IMPORT / COPY CANDIDATE'?'가져오기 가능':x==='REFERENCE'?'참고 전용':'제한된 라이선스'} key={x} className={status===x?'active':''} onClick={()=>setStatus(x)}>{x==='All'?'전체':x==='IMPORT / COPY CANDIDATE'?'가져오기 가능':x==='REFERENCE'?'참고 전용':'제한'}</button>)}</div></div><div className="sources-table"><div className="source-row header"><span>Source</span><span>Category / Stack</span><span>License</span><span>판정</span></div>{rows.map(s=><div className="source-row" key={s.source}><div><b>{s.source}</b><p>{s.what_it_provides}</p><div className="source-links">{safe(s.url)&&<a href={s.url} target="_blank" rel="noreferrer">Original <ExternalLink size={13}/></a>}{safe(s.github)&&<a href={s.github} target="_blank" rel="noreferrer"><Github size={13}/> GitHub</a>}</div></div><div><span>{s.category}</span><small>{s.stack}</small></div><div><b>{s.license}</b><small>{s.redistribution}</small>{safe(s.license_evidence)&&<a href={s.license_evidence} target="_blank" rel="noreferrer">License evidence ↗</a>}</div><div><span className={`source-status s-${s.recommendation.replace(/ /g, '-').replace(/\//g, '').toLowerCase()}`}>{s.recommendation === 'IMPORT / COPY CANDIDATE' ? '가져오기 가능' : s.recommendation === 'REFERENCE' ? '참고 전용' : '제한'}</span>{s.classification&&<small><b>{s.classification}</b></small>}<small>{s.caveat||s.attribution}</small></div></div>)}</div></section>
  </main>
}
