import type {DemoRecipe} from './recipes'

const specimen = `main{display:block;background:#e4e9ef;color:#34404f;container-type:inline-size}.specimen{height:100%;overflow:auto;padding:clamp(16px,4cqw,42px);display:flex;flex-direction:column;gap:clamp(16px,3cqw,30px)}.mast{display:flex;align-items:center;justify-content:space-between;gap:16px}.mast small{font-size:10px;letter-spacing:.18em}.specimen h1{font-size:clamp(28px,6cqw,64px);line-height:1.02;margin:0;letter-spacing:-.05em}.specimen h2{font-size:18px;margin:0 0 12px}.specimen p{font-size:13px;line-height:1.7;margin:8px 0}.style-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:clamp(20px,4cqw,40px);flex:1;align-items:center}.specimen button{color:inherit;border:0;min-height:44px;font-size:13px;padding:12px 20px}.tokens{display:flex;gap:16px;flex-wrap:wrap;font:10px monospace;letter-spacing:.05em}.tokens i{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px;vertical-align:middle}.note{color:#566577}.specimen button:focus-visible{outline:3px solid #596bd4;outline-offset:5px}@container(max-width:440px){.specimen{gap:14px}.style-grid{gap:18px}.specimen h1{font-size:30px}.detail-only,.tokens{display:none!important}.specimen button{padding:8px 12px;font-size:11px}.specimen p{font-size:11px}}`

export const batch1StyleRecipes: Record<string,DemoRecipe> = {
  'style-neumorphism': {
    html:`<div class="specimen"><header class="mast"><small>SOFT UI / 01</small><small class="detail-only">SURFACE STUDY</small></header><div class="style-grid"><section><h1>Quiet<br>by design.</h1><p class="detail-only note">배경과 같은 재료에서 솟아오르고,<br>안으로 들어가는 작은 표면들.</p><div class="controls"><button class="soft" aria-pressed="false">집중 모드</button><span class="state" role="status">편안한 하루</span></div></section><section class="surface"><div class="dial"><b>24°</b><span>ROOM / COMFORT</span></div><div class="inset detail-only"><span>밝기</span><input aria-label="조명 밝기" type="range" value="60"><output>60%</output></div></section></div><footer class="tokens"><span><i style="background:#e4e9ef"></i>SURFACE #E4E9EF</span><span>RAISED + INSET</span><span>RADIUS 24</span></footer></div>`,
    css:specimen+`.soft,.surface{background:#e4e9ef;box-shadow:10px 10px 24px #b9c1cd,-10px -10px 24px #ffffff}.surface{border-radius:28px;padding:clamp(18px,4cqw,40px)}.dial{width:clamp(90px,23cqw,210px);aspect-ratio:1;margin:auto;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-direction:column;box-shadow:inset 7px 7px 16px #bdc5d0,inset -7px -7px 16px #fff}.dial b{font-size:clamp(25px,5cqw,48px);font-weight:500}.dial span{font-size:8px;letter-spacing:.1em;margin-top:8px}.controls{display:flex;align-items:center;flex-wrap:wrap;gap:18px;margin-top:22px}.soft{border-radius:16px;transition:box-shadow 180ms,color 180ms}.soft[aria-pressed=true]{box-shadow:inset 5px 5px 12px #b9c1cd,inset -5px -5px 12px #fff;color:#4256b5}.state{font-size:11px}.inset{display:flex;align-items:center;gap:10px;margin-top:24px;padding:12px 16px;border-radius:12px;box-shadow:inset 3px 3px 7px #bbc3cf,inset -3px -3px 7px #fff;font-size:11px}.inset>span,.inset output{white-space:nowrap;flex-shrink:0}.inset input{min-width:0;width:100%;accent-color:#596bd4}@container(max-width:440px){.surface{padding:10px;border-radius:20px}.controls{margin-top:14px;gap:8px}.state{display:none}.dial span{font-size:6px}}`,
    js:`const button=document.querySelector('.soft');button.onclick=()=>{const active=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(active));document.querySelector('.state').textContent=active?'집중 모드 켜짐':'편안한 하루'};document.querySelector('input').oninput=e=>document.querySelector('output').textContent=e.target.value+'%';`,
    logic:'Near-background #e4e9ef surfaces use paired +10px/-10px 24px shadows (#b9c1cd/white). The dial and slider recess use paired inset shadows. A semantic toggle replaces raised with inset geometry in 180ms and announces its state. Detail adds room controls and token labels; card retains the raised button and recessed dial.',
    acceptance:'Raised AND inset geometry is visible on the same near-background material. Focus/click/Space toggles the inset control. Must not replace paired light/dark shadows with one generic gray drop shadow.'
  },
  'style-skeuomorphism': {
    html:`<div class="specimen"><header class="mast"><small>ANALOG / MATERIAL LAB</small><small class="detail-only">STEREO 02</small></header><div class="deck"><div class="screw tl"></div><div class="screw tr"></div><div class="screw bl"></div><div class="screw br"></div><div class="display"><span>LOCAL FM</span><strong>88.4</strong><span class="signal" role="status">STANDBY</span></div><div class="deck-controls"><button class="power" aria-pressed="false">▶ 재생</button><label class="volume">VOLUME<input aria-label="음량" type="range" min="0" max="100" value="42"><output>42</output></label></div></div><footer class="tokens"><span>BRUSHED METAL</span><span>BEVEL + GLOSS</span><span>TACTILE PRESS</span></footer><p class="detail-only">누르는 깊이와 빛의 변화로 상태를 읽는 아날로그 표면.</p></div>`,
    css:specimen+`main{background:repeating-linear-gradient(3deg,#5c4130 0 2px,#634834 3px 5px,#694d37 6px 9px);color:#f3e9da}.specimen{justify-content:center}.deck{position:relative;background:repeating-linear-gradient(0deg,#a2a7a6 0 1px,#b8bdbb 2px 3px);border:3px solid #d1d4cf;border-bottom-color:#565f5d;border-right-color:#656e6a;border-radius:18px;padding:clamp(22px,5cqw,50px);box-shadow:inset 0 2px 2px #fff9,0 16px 22px #261b1970}.display{border:5px solid #333e36;border-top-color:#18201b;border-radius:8px;background:linear-gradient(#425744,#708364);box-shadow:inset 0 4px 10px #1119,0 1px #eff4e0;display:flex;align-items:center;justify-content:space-between;padding:14px;color:#152d22;font-family:monospace}.display strong{font-size:clamp(32px,8cqw,78px);letter-spacing:-.07em;text-shadow:1px 1px #c5d9b13a}.display span{font-size:10px}.deck-controls{display:flex;gap:24px;align-items:center;margin-top:24px;color:#25342c}.power{background:linear-gradient(#fcfbec,#c1c5b1 48%,#a3a891 51%,#c5cab5);border-radius:8px;border:1px solid #707768!important;box-shadow:inset 0 2px #fff,0 5px #697261,0 8px 10px #0005;text-shadow:0 1px #fff;transition:transform 100ms,box-shadow 100ms}.power[aria-pressed=true],.power:active{transform:translateY(4px);box-shadow:inset 0 2px 4px #0005,0 1px #697261;background:linear-gradient(#a9b593,#c6d3b1)}.volume{display:flex;align-items:center;gap:12px;flex:1;font:9px monospace}.volume input{width:100%;min-width:0;accent-color:#35433b}.screw{position:absolute;width:8px;height:8px;border-radius:50%;background:linear-gradient(45deg,#ddd 40%,#343d39 43% 56%,#d0d6d1 60%);box-shadow:0 1px 2px #0008}.tl{left:9px;top:9px}.tr{right:9px;top:9px}.bl{left:9px;bottom:9px}.br{right:9px;bottom:9px}@container(max-width:440px){.deck{padding:14px}.specimen{gap:10px;padding:14px}.display{padding:5px;border-width:3px}.display span{font-size:8px}.display strong{font-size:34px}.deck-controls{margin-top:10px;gap:14px}.volume{gap:6px}.tokens{display:none}}`,
    js:`document.querySelector('.power').onclick=e=>{const b=e.currentTarget,on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));b.textContent=on?'Ⅱ 일시정지':'▶ 재생';document.querySelector('.signal').textContent=on?'PLAYING':'STANDBY'};document.querySelector('input').oninput=e=>document.querySelector('output').textContent=e.target.value;`,
    logic:'Independent analog receiver composition uses CSS wood grain, 1–3px brushed-metal lines, four screw heads, a recessed green LCD and a beveled/glossy physical switch. Pressing translates the control 4px and replaces its cast shadow with an inset shadow. Playback is a local visual state (no audio stream); volume updates a numeric output.',
    acceptance:'Material texture, bevel, inset lighting and a tactile pressed state are all visible. Must not substitute a flat glossy card or claim actual radio playback. System fonts and CSS-only materials stay offline.'
  },
  'style-bauhaus': {
    html:`<div class="specimen"><header class="mast"><small>FORM / FUNCTION</small><small>STUDY 03</small></header><div class="bau-grid"><section><h1>Build<br>with<br>purpose.</h1><p class="detail-only">질서는 단순한 도형에서 시작됩니다.<br>정렬, 비율, 그리고 필요한 색 하나.</p><button class="exhibit" aria-pressed="false">구성 전환 ↗</button></section><div class="geometry" aria-label="원, 삼각형, 사각형의 비대칭 구성"><i class="circle"></i><i class="triangle"></i><i class="square"></i><span>03</span></div></div><footer class="tokens"><span>RED #CF382B</span><span>BLUE #2455B2</span><span>YELLOW #EAC54B</span><span>GRID / 12</span></footer></div>`,
    css:specimen+`main{background:#ebe5d7;color:#171917}.mast{border-bottom:2px solid;padding-bottom:12px}.bau-grid{display:grid;grid-template-columns:1fr 1.15fr;gap:24px;align-items:stretch;flex:1}.bau-grid h1{font-size:clamp(34px,9cqw,90px);font-weight:900;line-height:.88;letter-spacing:-.07em}.exhibit{background:#171917;color:#fff!important;border-radius:0;margin-top:20px}.geometry{min-height:180px;position:relative;overflow:hidden;border-left:2px solid #171917;background:linear-gradient(90deg,transparent 49.6%,#171917 50%,transparent 50.4%)}.geometry i{position:absolute;transition:transform 350ms cubic-bezier(.2,.8,.2,1)}.circle{width:62%;aspect-ratio:1;border-radius:50%;background:#cf382b;left:8%;top:0}.triangle{width:64%;height:72%;clip-path:polygon(50% 0,100% 100%,0 100%);background:#eac54b;right:0;bottom:0}.square{width:45%;height:42%;background:#2455b2;left:3%;bottom:0}.geometry span{position:absolute;right:4%;top:0;font-size:clamp(24px,5cqw,50px);writing-mode:vertical-rl}.alternate .circle{transform:translate(35%,45%)}.alternate .triangle{transform:translate(-35%,-20%)}.tokens{border-top:2px solid;padding-top:14px}@container(max-width:440px){.specimen{gap:12px;padding:14px}.mast{padding-bottom:7px}.bau-grid{gap:12px}.bau-grid h1{font-size:32px}.geometry{min-height:110px}.exhibit{margin-top:10px;min-height:28px!important;padding:6px 8px!important;font-size:9px!important}}`,
    js:`document.querySelector('.exhibit').onclick=e=>{const active=document.querySelector('.specimen').classList.toggle('alternate');e.currentTarget.setAttribute('aria-pressed',String(active))};`,
    logic:'Clean-room Bauhaus specimen: asymmetric 1:1.15 grid, functional 2px rules, heavy system sans typography, red circle/blue rectangle/yellow triangle, and neutral paper. A semantic toggle repositions primary geometry over 350ms without changing the underlying grid; reduced motion removes the transition.',
    acceptance:'Primary geometry, asymmetry, strong functional typography and restrained primary colors identify Bauhaus at both sizes. Must not become a generic centered geometric SaaS card. No design-isms or marketplace code, text, images or template assets are copied.'
  },
  'style-japandi': {
    html:`<div class="specimen"><header class="mast"><small>STILL / LIVING</small><span class="edition">自然 · 04</span></header><div class="jap-grid"><section><small>OBJECTS FOR A QUIETER DAY</small><h1>Room<br>to breathe.</h1><p class="detail-only">소박한 재료와 충분한 여백.<br>매일 머무는 공간에 작은 균형을 만듭니다.</p><button class="tone" aria-pressed="false">저녁빛 보기 →</button></section><div class="still-life" role="img" aria-label="나뭇가지와 도자기, 자연석의 정물"><i class="stem"></i><i class="leaf l1"></i><i class="leaf l2"></i><i class="vase"></i><i class="stone"></i><div class="plinth"></div></div></div><footer class="tokens"><span>LINEN #EDE7DA</span><span>CLAY #AE947D</span><span>INK #344037</span><span>SPACE / 24 · 48</span></footer><p class="detail-only caption" role="status">오전의 부드러운 자연광</p></div>`,
    css:specimen+`main{background:#ede7da;color:#344037}.specimen{background:radial-gradient(ellipse at 80% 15%,#fff8,transparent 60%);transition:background-color 400ms}.mast{border-bottom:1px solid #34403740;padding-bottom:14px}.edition{font-family:serif;font-size:12px}.jap-grid{display:grid;grid-template-columns:1fr 1fr;gap:5%;flex:1;align-items:center}.jap-grid h1{font-family:Georgia,serif;font-weight:400;letter-spacing:-.06em;font-size:clamp(34px,8cqw,88px);margin-top:20px;line-height:1.02}.jap-grid small{font-size:9px;letter-spacing:.12em}.tone{background:transparent;border-bottom:1px solid #344037!important;padding:10px 0!important;margin-top:20px;border-radius:0}.still-life{height:100%;min-height:240px;position:relative;background:linear-gradient(110deg,#e3dac9,#f4efe5);overflow:hidden}.vase{position:absolute;width:35%;height:44%;left:34%;bottom:13%;border-radius:32% 35% 40% 40%;background:linear-gradient(100deg,#826c59,#bea68d 45%,#dac5a8 70%,#9d8772);box-shadow:15px 10px 22px #66544530}.stem{position:absolute;width:2px;height:62%;left:49%;top:3%;background:#4f573e;rotate:14deg}.leaf{position:absolute;background:#69775a;width:27%;height:9%;border-radius:90% 0 90% 0;rotate:-20deg}.l1{left:48%;top:15%}.l2{left:24%;top:28%;rotate:36deg}.stone{position:absolute;width:39%;height:14%;left:9%;bottom:9%;border-radius:60% 50% 35% 40%;background:linear-gradient(#7d8475,#505d50);box-shadow:6px 6px 12px #3f493433}.plinth{position:absolute;height:9%;inset:auto 0 0;background:repeating-linear-gradient(2deg,#b7a18a 0 2px,#bfad93 3px 6px)}.dusk{background-color:#d7c8b5}.dusk .still-life{background:linear-gradient(120deg,#c6ac90,#e8cbab)}.caption{font-family:Georgia,serif;color:#687361}.tokens{border-top:1px solid #34403740;padding-top:15px}@container(max-width:440px){.specimen{padding:14px;gap:10px}.mast{padding-bottom:8px}.still-life{min-height:120px}.jap-grid h1{font-size:30px;margin-top:6px}.jap-grid small{font-size:6px}.tone{margin-top:8px;min-height:25px!important;padding:5px 0!important;font-size:10px!important}}`,
    js:`document.querySelector('.tone').onclick=e=>{const dusk=document.querySelector('.specimen').classList.toggle('dusk');e.currentTarget.setAttribute('aria-pressed',String(dusk));e.currentTarget.textContent=dusk?'아침빛 보기 →':'저녁빛 보기 →';document.querySelector('.caption').textContent=dusk?'저녁의 따뜻한 빛':'오전의 부드러운 자연광'};`,
    logic:'Clean-room Japandi uses linen/clay/olive neutrals, Georgia display type with system sans labels, generous 24/48px rhythm and CSS-only ceramic/wood/stone still life. Morning/evening controls change local lighting without external photos or fonts. Detail shows material/palette captions; card retains the still life and restrained type pairing.',
    acceptance:'Natural materials, warm neutrals and deliberate editorial whitespace identify Japandi rather than generic beige SaaS. The lighting toggle works by pointer and keyboard. No marketplace/design-isms assets, code or prose are copied.'
  }
}

// Keep material objects and geometric forms proportionate in tall mobile Detail frames.
batch1StyleRecipes['style-japandi'].css += '.still-life{width:100%;height:auto;aspect-ratio:1;min-height:0;align-self:center}'
batch1StyleRecipes['style-bauhaus'].css += '.geometry{aspect-ratio:1;align-self:center;width:100%}'
