import { batch1Recipes } from './batch1Recipes'
import { fidelityRecipes, densityPolicy } from './fidelityRecipes'
export { densityPolicy } from './fidelityRecipes'
import hubLicense from '../../../LICENSE?raw'
import meteorLicense from '../../../docs/licenses/Magic-UI-MIT.txt?raw'
export type DemoRecipe = { html: string; css: string; js?: string; logic: string; acceptance: string; sourceNotes?: string; notices?: string; responsive?: string }
export const recipes: Record<string, DemoRecipe> = {}
const add = (keys: string[], recipe: DemoRecipe) => keys.forEach(key => { recipes[key] = recipe })
const title = '<h1>DESIGN<br>IN MOTION</h1>'
const pointer = `const stage=document.querySelector('main');stage.addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType==='touch')return;const r=stage.getBoundingClientRect();stage.style.setProperty('--x',(e.clientX-r.left)+'px');stage.style.setProperty('--y',(e.clientY-r.top)+'px');stage.style.setProperty('--nx',String((e.clientX-r.left)/r.width-.5));stage.style.setProperty('--ny',String((e.clientY-r.top)/r.height-.5))});stage.addEventListener('pointerleave',()=>{stage.style.setProperty('--nx','0');stage.style.setProperty('--ny','0')});`
add(['glass-card','style-glass','spotlight-card','glow-card'], {
 html:'<div class="orb"></div><article tabindex="0"><small>MATERIAL / 04</small><h1>Glass<br>in focus.</h1><p>투명한 표면 · 빛 · 깊이</p></article>',
 css:`main{background:linear-gradient(135deg,#112545,#502d81 55%,#ef874e)}.orb{position:absolute;width:220px;height:220px;border-radius:50%;background:#fd9d5e;left:12%;top:10%;box-shadow:200px 160px 0 #6949ea}article{position:relative;padding:28px;width:min(78%,350px);border:1px solid #ffffff70;border-radius:24px;background:radial-gradient(circle at var(--x,50%) var(--y,40%),#ffffff38,transparent 70%),#ffffff14;backdrop-filter:blur(16px) saturate(1.4);box-shadow:inset 0 1px #fff8,0 24px 60px #0005}h1{font-size:clamp(32px,8vw,62px)}p{font-size:12px;color:#fff}article:focus-visible{outline:3px solid #f7ff91}`,
 js:pointer, logic:'상대 위치 배경 위에 반투명 article을 놓고 blur 16px, saturate 1.4, 1px 밝은 테두리를 적용한다. pointer 좌표를 CSS 변수로 전달해 radial highlight를 이동한다. 이 효과는 frosted glass이며 굴절 렌즈와 구분한다.', acceptance:'뒤의 색상 원이 흐릿하게 비치고 article의 글자는 선명하다. 포인터 이동 시 highlight가 이동한다.'
})
add(['liquid-lens','liquid-lens-effect','rgb-lens','style-liquid'], {
 html:'<canvas aria-label="배경 글자와 격자를 굴절시키는 포인터 렌즈"></canvas><span class="hint">포인터를 움직여 굴절을 확인하세요</span><p class="fallback" hidden>WebGL을 사용할 수 없어 정적 배경을 표시합니다.</p>',
 css:'main{background:linear-gradient(125deg,#d1b9f9,#74b9dc,#f0ad75)}canvas{width:100%;height:100%;position:absolute;inset:0}.hint{color:#152039}.fallback{z-index:1;color:#152039}',
 logic:'Canvas 2D로 글자와 격자를 포함한 배경 텍스처를 만든다. WebGL fragment shader에서 픽셀 좌표와 렌즈 중심의 거리를 계산한다. 반경 내부에 구면 법선 기반 UV 변위를 적용하고 R/G/B를 1.025/1/0.975 배율로 분리 sampling한다. 포인터 위치는 0.12 보간하고 속도에 따라 x축을 최대 12% 늘린다. 가장자리에 specular ring을 합성한다. DPR은 1.5로 제한한다. Reduced motion에서는 중앙 렌즈 한 프레임만 그린다.',
 acceptance:'렌즈 안의 글자와 격자가 바깥과 다르게 휘고 확대된다. 테두리에 RGB 분리와 밝은 반사가 보인다. 이동 후 중심이 부드럽게 수렴하고 WebGL 실패 시 fallback을 표시한다.',
 js:`const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl',{alpha:false});if(!gl){document.querySelector('.fallback').hidden=false}else{
const vert='attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}';
const frag='precision mediump float;varying vec2 uv;uniform sampler2D tex;uniform vec2 size,center;uniform float stretch;void main(){vec2 pos=uv*size;vec2 delta=pos-center;delta.x/=stretch;float radius=min(size.x,size.y)*.28;float d=length(delta)/radius;vec2 coord=vec2(uv.x,1.-uv.y);vec3 color=texture2D(tex,coord).rgb;if(d<1.){float z=sqrt(max(0.,1.-d*d));vec2 shift=delta/size*(.22*z+.035);shift.y=-shift.y;vec2 q=coord-shift;color=vec3(texture2D(tex,q-shift*.025).r,texture2D(tex,q).g,texture2D(tex,q+shift*.025).b);float rim=smoothstep(.84,1.,d);float spec=pow(max(0.,dot(normalize(vec3(delta/radius,z)),normalize(vec3(-.5,.7,1.)))),18.);color+=rim*.28+spec*.55;}gl_FragColor=vec4(color,1.);}';
const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vert));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,frag));gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
let w=1,h=1,x=.5,y=.5,tx=.5,ty=.5;const resize=()=>{w=canvas.clientWidth;h=canvas.clientHeight;const dpr=Math.min(devicePixelRatio,1.5);canvas.width=w*dpr;canvas.height=h*dpr;gl.viewport(0,0,canvas.width,canvas.height);const scene=document.createElement('canvas');scene.width=1024;scene.height=768;const c=scene.getContext('2d');const g=c.createLinearGradient(0,0,1024,768);g.addColorStop(0,'#d4b9f5');g.addColorStop(.5,'#77c5da');g.addColorStop(1,'#f8ad77');c.fillStyle=g;c.fillRect(0,0,1024,768);c.strokeStyle='#21365544';for(let i=0;i<1100;i+=64){c.beginPath();c.moveTo(i,0);c.lineTo(i,768);c.stroke();c.beginPath();c.moveTo(0,i);c.lineTo(1024,i);c.stroke()}c.fillStyle='#20364d';c.font='900 118px system-ui';c.fillText('LIQUID',90,320);c.fillText('GLASS',280,460);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,scene)};resize();const ro=new ResizeObserver(resize);ro.observe(canvas);
canvas.addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType==='touch')return;const r=canvas.getBoundingClientRect();tx=(e.clientX-r.left)/w;ty=1-(e.clientY-r.top)/h});canvas.addEventListener('pointerleave',()=>{tx=.5;ty=.5});
loop(()=>{x+=(tx-x)*.12;y+=(ty-y)*.12;gl.uniform2f(gl.getUniformLocation(program,'size'),w,h);gl.uniform2f(gl.getUniformLocation(program,'center'),x*w,y*h);gl.uniform1f(gl.getUniformLocation(program,'stretch'),1+Math.min(.12,Math.abs(tx-x)));gl.drawArrays(gl.TRIANGLES,0,6)});window.addEventListener('pagehide',()=>{ro.disconnect();gl.getExtension('WEBGL_lose_context')?.loseContext()},{once:true});}`
})
add(['aurora','gradient-mesh'],{html:'<i class="field one"></i><i class="field two"></i><i class="field three"></i>'+title,css:'main{background:#111628}.field{position:absolute;width:85%;height:60%;border-radius:50%;filter:blur(clamp(24px,5vw,65px));opacity:.8;animation:drift 10s ease-in-out infinite alternate}.one{background:#36e0ad;left:-20%;top:-20%;transform:rotate(-25deg)}.two{background:#7264ec;right:-20%;bottom:-20%;animation-delay:-4s}.three{background:#df7aba;width:50%;height:30%;left:35%;top:40%;animation-delay:-7s}@keyframes drift{to{transform:translate(20%,30%) rotate(30deg) scale(1.2)}}',logic:'세 개의 큰 타원 색상장을 컨테이너 폭에 따라 blur 24–65px로 혼합한다. 10초 alternate 이동을 서로 다른 음수 delay로 시작하여 반복이 겹치지 않게 한다.',acceptance:'독립된 색상장이 천천히 이동하며 섞인다. 글자가 항상 선명하고 배경은 영역 밖으로 넘치지 않는다.'})
add(['spotlight','spotlight-background'],{html:'<div class="light"></div>'+title,css:'main{background:#121d2b;background-image:radial-gradient(#ffffff24 1px,transparent 1px);background-size:24px 24px}.light{position:absolute;left:var(--x,50%);top:var(--y,50%);width:clamp(200px,45vw,600px);height:clamp(200px,45vw,600px);transform:translate(-50%,-50%);border-radius:50%;background:radial-gradient(#b4acff99,transparent 70%);transition:left 180ms ease-out,top 180ms ease-out;pointer-events:none}',js:pointer,logic:'pointer 좌표를 상대 위치 CSS 변수로 전달한다. container-scaled 200–600px radial light를 중앙 정렬하고 180ms ease-out으로 추종한다.',acceptance:'빛이 포인터를 따라가며 점 격자를 밝힌다. touch/reduced motion에서는 중앙에 머문다.'})
// Separate recipes keep each canonical interaction distinct.
add(['scroll-reveal','sticky-story','horizontal-scroll'],{html:'<div class="scroller" tabindex="0" aria-label="스크롤 데모"><aside>SCROLL<br>TO DISCOVER ↓</aside><div class="steps">'+['SEE','NAME','COPY','BUILD'].map((x,i)=>`<section><small>0${i+1}</small><h1>${x}</h1></section>`).join('')+'</div></div>',css:'.scroller{width:100%;height:100%;overflow:auto;padding:22px;scrollbar-gutter:stable}.scroller aside{padding:20px;color:#d9ff8c}.steps section{min-height:220px;margin:18px 0;padding:24px;background:#283347;border-radius:18px;opacity:.1;transform:translateY(35px);transition:opacity .6s,transform .6s}.steps section.visible{opacity:1;transform:none}',js:`const root=document.querySelector('.scroller');const io=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{root,threshold:.25});document.querySelectorAll('.steps section').forEach(el=>io.observe(el));window.addEventListener('pagehide',()=>io.disconnect(),{once:true});`,logic:'높이가 제한된 scroll container를 observer root로 사용한다. 각 section의 25% 진입 시 opacity 1, translateY 0으로 전환한다. 키보드로 컨테이너를 스크롤할 수 있다.',acceptance:'시간 기반 반복이 아니라 실제 스크롤 위치에 따라 section이 나타난다.'})
recipes['sticky-story']={...recipes['sticky-story'],css:recipes['sticky-story'].css+'.scroller{display:grid;grid-template-columns:40% 60%}.scroller aside{position:sticky;top:0;height:130px;padding:12px}.steps section{opacity:1;transform:none}',js:'',logic:'scroll container 내부에서 왼쪽 aside에 position:sticky;top:0을 적용한다. 오른쪽 4개 section만 긴 문서 흐름으로 배치한다.',acceptance:'오른쪽 내용이 스크롤되는 동안 왼쪽 제목은 같은 위치에 남는다.'}
recipes['horizontal-scroll']={...recipes['horizontal-scroll'],css:'.scroller{width:100%;height:100%;overflow:auto}.scroller aside{padding:16px}.steps{display:flex;width:max-content;gap:16px;padding:20px}.steps section{width:240px;padding:30px;background:#283347;border-radius:18px}',js:`const el=document.querySelector('.scroller');el.addEventListener('wheel',e=>{const next=Math.max(0,Math.min(el.scrollWidth-el.clientWidth,el.scrollLeft+e.deltaY));if(next!==el.scrollLeft){e.preventDefault();el.scrollLeft=next}},{passive:false});`,logic:'가로 flex track에 240px 패널을 나열한다. wheel deltaY를 scrollLeft에 반영하고 양끝에서는 preventDefault하지 않아 페이지 스크롤을 풀어준다. 모바일 native swipe와 키보드 좌우키를 유지한다.',acceptance:'세로 wheel이 가로 패널을 이동시키고 끝에 도달하면 페이지 스크롤을 막지 않는다.'}
add(['text-reveal','blur-reveal','split-text','gradient-text','shimmer-text','rotating-words','typewriter','scramble-text','number-ticker'],{html:'<h1 class="text" aria-label="Design in motion">'+['Design','in','motion'].map((s,i)=>`<span style="--i:${i}" aria-hidden="true">${s}</span>`).join(' ')+'</h1><button class="replay">다시 보기</button>',css:'.text{overflow:hidden;text-align:center;font-size:clamp(28px,8vw,68px)}.text span{display:inline-block;animation:reveal .8s cubic-bezier(.2,.8,.2,1) both;animation-delay:calc(var(--i)*120ms)}@keyframes reveal{from{opacity:0;transform:translateY(110%)}to{opacity:1;transform:none}}.replay{position:absolute;bottom:18px;font-size:12px;padding:8px 14px}',js:`document.querySelector('.replay').onclick=()=>document.getAnimations().forEach(a=>{a.cancel();a.play()});`,logic:'각 단어를 inline-block span으로 분리하고 overflow hidden 제목 안에서 translateY 110%→0, opacity 0→1을 800ms 적용한다. delay는 120ms씩 증가한다. 접근성 이름은 완전한 문장으로 유지한다.',acceptance:'단어들이 120ms 간격으로 차례대로 나타나고 다시 보기로 재생된다.'})
recipes['blur-reveal']={...recipes['blur-reveal'],css:recipes['blur-reveal'].css+'@keyframes reveal{from{opacity:0;filter:blur(16px)}to{opacity:1;filter:blur(0)}}',logic:'각 단어의 blur를 16px에서 0으로 800ms 전환하며 opacity를 함께 증가시킨다.',acceptance:'흐릿한 글자가 선명하게 나타난다.'}
recipes['split-text']={...recipes['split-text'],html:'<h1 class="text" aria-label="MOTION">'+[...'MOTION'].map((s,i)=>`<span aria-hidden="true" style="--i:${i}">${s}</span>`).join('')+'</h1><button class="replay">다시 보기</button>',logic:'MOTION을 6개 aria-hidden 문자 span으로 분리하고 120ms 간격으로 translateY reveal한다. 제목에는 완전한 접근성 이름을 부여한다.',acceptance:'단어가 아니라 개별 문자가 순서대로 나타난다.'}
for(const key of ['gradient-text','shimmer-text'])recipes[key]={html:'<h1 class="color-text">COLOR<br>IN MOTION</h1>',css:'.color-text{font-size:clamp(36px,10vw,76px);background:linear-gradient(110deg,#bba7ff,#80ddea,#fff,#c5a3ff);background-size:250% 100%;background-clip:text;color:transparent;animation:color 3s linear infinite}@keyframes color{to{background-position:250% 0}}',logic:'250% 폭의 gradient를 text에 clip하고 background-position을 3초 linear 반복 이동한다.',acceptance:'색상 띠가 글자 내부에서만 이동한다.'}
for(const key of ['typewriter','scramble-text','number-ticker','rotating-words'])recipes[key]={html:'<h1 class="output" aria-label="'+(key==='number-ticker'?'1,284':'Design in motion')+'"><span aria-hidden="true">Design in motion</span></h1><button class="replay">다시 보기</button>',css:'.output{font-size:clamp(28px,8vw,68px);text-align:center;min-height:90px}.replay{position:absolute;bottom:18px;padding:8px 14px}',js:`const output=document.querySelector('.output span'),target='Design in motion';let start=performance.now();document.querySelector('.replay').onclick=()=>{start=performance.now()};loop(now=>{const t=reduced.matches?10000:now-start;${key==='typewriter'?"output.textContent=target.slice(0,Math.min(target.length,Math.floor(t/95)));":key==='number-ticker'?"const p=Math.min(1,t/1600);output.textContent=Math.round(1284*(1-Math.pow(1-p,3))).toLocaleString();":key==='scramble-text'?"output.textContent=[...target].map((c,i)=>i<t/65?c:'<>01{}'[Math.floor(Math.random()*6)]).join('');":"output.textContent=['Design','Create','Build'][Math.floor(t/1500)%3];"}});`,logic:key==='number-ticker'?'1600ms 동안 easeOutCubic 보간으로 0→1284 증가하고 목표값에서 정지한다. 다시 보기로 초기화한다.':key==='scramble-text'?'65ms마다 확정할 문자 수를 늘린다. 미확정 자리만 무작위 기호로 표시하며 최종 문장에서 멈춘다.':key==='typewriter'?'95ms당 한 문자를 표시하고 완전한 문장에서 멈춘다. 다시 보기로 시작 시각을 초기화한다.':'1500ms마다 Design/Create/Build 단어를 교체한다. Reduced motion에는 정적인 최종 단어를 표시한다.',acceptance:key==='number-ticker'?'최종값 1,284에 수렴하고 0으로 무한 반복하지 않는다.':'문자가 잘리지 않고 완성되며 다시 보기와 reduced motion이 동작한다.'}
add(['marquee'],{html:'<div class="track">'+[0,1].map(i=>`<div ${i?'aria-hidden="true"':''}>DESIGN ✦ MOTION ✦ GLASS ✦ TYPE ✦ </div>`).join('')+'</div>',css:'.track{display:flex;width:max-content;animation:marquee 16s linear infinite;font-size:48px;font-weight:900}.track div{white-space:nowrap;padding-right:32px}@keyframes marquee{to{transform:translateX(-50%)}}main:hover .track,main:focus-within .track{animation-play-state:paused}',logic:'동일한 콘텐츠를 두 번 복제하고 두 번째는 aria-hidden으로 둔다. 전체 track을 -50% 이동하여 시작/끝 이음새를 맞춘다. hover 시 정지한다.',acceptance:'루프 경계에서 빈 공간이나 점프가 없고 hover에서 정지한다.'})
add(['animated-border','shimmer-button'],{html:'<button class="border"><span>직접 움직이는 테두리 ↗</span></button>',css:'.border{position:relative;padding:2px;overflow:hidden;border:0;border-radius:20px;background:#344057}.border:before{content:"";position:absolute;inset:-180%;background:conic-gradient(transparent 70%,#a6eeff,#fff,transparent);animation:spin 3s linear infinite}.border span{display:block;position:relative;border-radius:18px;padding:clamp(24px,4vw,48px);font-size:clamp(14px,2vw,22px);background:#172136;color:white}@keyframes spin{to{transform:rotate(360deg)}}',logic:'버튼 바깥 래퍼를 overflow hidden으로 두고 큰 conic-gradient pseudo-element를 회전한다. 안쪽 면은 2px inset으로 테두리만 노출한다.',acceptance:'밝은 선이 테두리를 순환하고 콘텐츠 위를 덮지 않는다.'})
add(['ripple','confetti'],{html:'<button class="trigger">클릭 · Enter로 재생</button><div class="bursts" aria-hidden="true"></div>',css:'.trigger{padding:22px;border-radius:99px;background:#d9ff83;color:#172136;border:0}.bursts{position:absolute;inset:0;pointer-events:none}.burst{position:absolute;left:var(--x);top:var(--y);width:12px;height:12px;background:hsl(var(--h) 85% 65%);animation:burst 850ms ease-out forwards}@keyframes burst{to{transform:translate(var(--dx),var(--dy)) rotate(300deg);opacity:0}}',js:`document.querySelector('.trigger').addEventListener('click',e=>{if(reduced.matches)return;const r=document.querySelector('main').getBoundingClientRect();document.querySelector('.bursts').replaceChildren();const count=Math.max(16,Math.min(64,Math.round(r.width*r.height/7000))),travel=Math.min(r.width,r.height)*.38;for(let i=0;i<count;i++){const b=document.createElement('i');b.className='burst';b.style.cssText='--x:'+(e.detail?e.clientX-r.left:r.width/2)+'px;--y:'+(e.detail?e.clientY-r.top:r.height/2)+'px;--scale:'+Math.hypot(r.width,r.height)/6+';--h:'+i*27+';--dx:'+Math.cos(i)*travel+'px;--dy:'+(Math.sin(i)*travel+travel*.3)+'px';document.querySelector('.bursts').append(b);b.addEventListener('animationend',()=>b.remove(),{once:true})}});`,logic:'실제 button click에서 면적/7000 기준 16–64개 조각을 만든다. 이동 반경은 짧은 변의 38%다. 새 입력은 이전 burst를 교체하여 활성 DOM cap을 유지한다. 각 조각은 다른 hue와 삼각함수 방향을 가지며 850ms 후 animationend에서 제거한다. 키보드 activation은 중앙 좌표를 사용한다.',acceptance:'버튼 click/Enter에서만 burst가 발생하고 조각 DOM은 재생 후 제거된다.'})
recipes.ripple={...recipes.ripple,css:recipes.ripple.css+'.burst{border-radius:50%;border:2px solid white;background:transparent!important}@keyframes burst{to{transform:translate(-50%,-50%) scale(var(--scale));opacity:0}}',js:recipes.ripple.js!.replace('i<count','i<1'),logic:'click 좌표에 원 하나를 만들고 850ms 동안 컨테이너 대각선에 비례하는 반경으로 확대하며 투명하게 한다. 새 입력은 이전 burst를 교체한다. 키보드는 버튼 중앙을 사용하고 animationend에 제거한다.',acceptance:'포인터 click 위치에서 원이 퍼지고 키보드 Enter도 중앙 ripple을 만든다.'}

export function recipeHtml(kind: string, options?: { variant?: 'detail' | 'card' }): string | null {
 const r=recipes[kind];if(!r)return null
 const variant = options?.variant ?? 'detail';
 const {html,css,js}=r;
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${kind} — Hub Original</title><style>*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;font-family:system-ui,sans-serif}main{position:relative;width:100%;height:100%;min-height:0;overflow:hidden;display:flex;align-items:center;justify-content:center;background:#141e30;color:#fff;isolation:isolate}h1{position:relative;z-index:1;font-size:clamp(32px,9vw,72px);line-height:1.05;letter-spacing:-.055em;margin:16px 0}small{font-size:10px;letter-spacing:.13em}button{font:inherit;cursor:pointer}button:focus-visible,[tabindex]:focus-visible{outline:3px solid #e4ff93;outline-offset:4px}.hint{position:absolute;bottom:16px;font-size:11px;z-index:2}.replay{border:1px solid #ffffff50;border-radius:99px;background:#ffffff10;color:#fff;min-height:36px}${css}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}.steps section{opacity:1;transform:none}.object{transform:none!important}}@media(pointer:coarse){.object{transform:none!important}}</style></head><body><main data-variant="${variant}" data-density="${densityPolicy(kind)}">${html}</main><script>${kind === 'meteors' ? '/* Adapted from Magic UI meteor head/tail structure.\n'+meteorLicense+'\n*/' : ''}/* ${hubLicense} */
${r.notices ? '/* '+r.notices.replaceAll('*/','* /')+' */' : ''}
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='drh:pointerleave')return;document.querySelector('main').dispatchEvent(new PointerEvent('pointerleave'));document.querySelector('canvas')?.dispatchEvent(new PointerEvent('pointerleave'))});
const reduced=matchMedia('(prefers-reduced-motion:reduce)');let raf=0;let render;function loop(fn){render=fn;const tick=now=>{const keep=fn(now);if(keep!==false&&!reduced.matches&&!document.hidden)raf=requestAnimationFrame(tick)};tick(performance.now())}function restart(){cancelAnimationFrame(raf);document.querySelectorAll('.meteor,.field').forEach(el=>el.style.animationPlayState=document.hidden?'paused':'running');if(render&&!document.hidden)loop(render)}document.addEventListener('visibilitychange',restart);reduced.addEventListener('change',restart);window.addEventListener('pagehide',()=>cancelAnimationFrame(raf),{once:true});
${js??''}
</script></body></html>`
}

// These examples use original, embedded SVG art; no remote photo or asset license is required.
const art=(hue:number)=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400" viewBox="0 0 640 400"><rect width="640" height="400" fill="hsl(${hue},45%,18%)"/><circle cx="440" cy="130" r="86" fill="hsl(${hue+65},85%,72%)"/><path d="M0 350L180 90 350 400H0Z" fill="hsl(${hue+30},65%,52%)"/><path d="M250 400L470 210 640 400Z" fill="hsl(${hue+100},60%,68%)"/><text x="30" y="355" fill="white" font-family="sans-serif" font-size="36">FORM / ${hue}</text></svg>`)
add(['image-trail'],{html:'<h1>IMAGE<br>TRAIL</h1><span class="hint">포인터를 움직이세요 · 터치는 탭</span>',css:'.trail{position:absolute;width:clamp(90px,18vw,180px);border-radius:12px;pointer-events:none;z-index:3;animation:trail 850ms ease-out both}@keyframes trail{0%{opacity:0;transform:translate(-50%,-50%) scale(.5) rotate(-12deg)}20%{opacity:1;transform:translate(-50%,-50%) scale(1)}100%{opacity:0;transform:translate(-50%,-90%) scale(.85) rotate(10deg)}}',js:`const images=${JSON.stringify([art(210),art(300),art(30),art(150)])};const stage=document.querySelector('main');let last={x:-1000,y:-1000},n=0;function emit(e){if(reduced.matches)return;const r=stage.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(e.type==='pointermove'&&Math.hypot(x-last.x,y-last.y)<40)return;last={x,y};if(stage.querySelectorAll('img').length>=Math.max(8,Math.min(24,Math.round(r.width*r.height/22000))))stage.querySelector('img').remove();const img=new Image();img.alt='';img.src=images[n++%images.length];img.className='trail';img.style.left=x+'px';img.style.top=y+'px';stage.append(img);img.addEventListener('animationend',()=>img.remove(),{once:true})}stage.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')emit(e)});stage.addEventListener('pointerdown',emit);`,logic:'40px 이상 pointer 이동 시 4개 내장 SVG 이미지 중 다음 이미지를 생성한다. 동시 노드는 면적/22000 기준 8–24개로 제한하고 850ms 등장/상승/소멸 후 animationend에서 제거한다. touch는 tap으로 한 장을 생성한다.',acceptance:'텍스트 타일 대신 실제 이미지가 경로에 나타나고 사라진다. 외부 이미지 다운로드가 없고 반복 입력에도 면적 기준 8–24장 cap을 넘지 않는다.'})
add(['image-reveal','comparison-slider'],{html:`<div class="media"><img alt="원본 기하학 풍경" src="${art(210)}"><div class="overlay"><img alt="색상을 변경한 기하학 풍경" src="${art(300)}"></div><div class="divider"></div></div><input aria-label="이미지 비교 위치" type="range" min="0" max="100" value="50">`,css:'.media{position:absolute;inset:0}.media img{width:100%;height:100%;object-fit:cover}.overlay{position:absolute;inset:0;clip-path:inset(0 calc(100% - var(--position,50%)) 0 0)}.divider{position:absolute;left:var(--position,50%);top:0;bottom:0;width:2px;background:white}input{position:absolute;bottom:16px;left:10%;width:80%;z-index:3;accent-color:#d9ff83}',js:`document.querySelector('input').addEventListener('input',e=>document.querySelector('main').style.setProperty('--position',e.target.value+'%'));`,logic:'동일 크기의 두 이미지를 겹친다. 상단 이미지만 clip-path inset으로 자르고 native range 0~100 값을 경계선과 clip 변수에 함께 전달한다.',acceptance:'이미지 자체가 늘어나지 않고 경계선이 움직이며 두 색상 버전을 비교한다. 키보드 화살표와 touch range가 동작한다.'})
recipes['image-reveal']={...recipes['image-reveal'],html:`<div class="media"><img alt="기하학 풍경" src="${art(210)}"></div><button class="replay">다시 보기</button>`,css:'.media{position:absolute;inset:0;animation:unmask 1.2s cubic-bezier(.2,.8,.2,1) both}.media img{width:100%;height:100%;object-fit:cover}.replay{position:absolute;bottom:16px;z-index:2;padding:8px 14px}@keyframes unmask{from{clip-path:inset(0 100% 0 0)}to{clip-path:inset(0)}}',js:`document.querySelector('.replay').onclick=()=>document.getAnimations().forEach(a=>{a.cancel();a.play()});`,logic:'이미지의 clip-path inset right를 100%에서 0으로 1.2초 동안 이동한다. 이미지 크기는 고정하고 마스크만 변경한다.',acceptance:'실제 이미지가 왼쪽부터 드러나고 다시 보기 버튼으로 반복할 수 있다.'}
recipes.aurora={...recipes.aurora,css:recipes.aurora.css+'.field{width:120%;height:22%;border-radius:50%;filter:blur(clamp(18px,3vw,40px));transform:rotate(-25deg)}.one{top:5%;left:-20%}.two{top:40%;left:0}.three{top:75%;left:-15%;width:110%}',logic:'길고 좁은 세 개의 빛 리본을 -25도로 기울이고 blur 20px로 혼합한다. 각 리본을 10초 alternate로 독립 이동시켜 원형 mesh와 구분한다.',acceptance:'원형 blob이 아니라 길게 휘어진 aurora 빛 띠가 겹쳐 흐른다.'}
recipes['glow-card']={...recipes['glow-card'],css:recipes['glow-card'].css+'article{transition:box-shadow 220ms}article:hover,article:focus-visible{box-shadow:0 0 15px #aaffee,0 0 65px #a088ff,inset 0 1px #fff8}',acceptance:'hover와 keyboard focus에서 카드 바깥쪽 halo가 밝아지고 해제하면 줄어든다.'}
recipes['shimmer-button']={html:'<button class="shimmer">새로운 시작 ↗</button>',css:'.shimmer{position:relative;overflow:hidden;border:1px solid #fff6;border-radius:99px;padding:clamp(18px,3vw,32px) clamp(24px,4vw,48px);font-size:clamp(14px,2vw,22px);background:#544697;color:white}.shimmer:after{content:"";position:absolute;inset:-50%;background:linear-gradient(110deg,transparent 35%,#ffffff80,transparent 65%);animation:sweep 2.5s infinite}@keyframes sweep{from{transform:translateX(-100%)}to{transform:translateX(100%)}}',logic:'버튼 내부의 반투명 대각선 gradient를 -100%에서 100%로 2.5초 이동한다. overflow hidden으로 버튼 안에서만 보이게 한다.',acceptance:'밝은 빛이 버튼 표면을 가로지르고 테두리 회전과는 구분된다.'}
add(['retro-grid'],{html:'<div class="sun"></div><div class="grid"></div><h1>RETRO / 99</h1>',css:'main{background:linear-gradient(#170e36,#3d1750)}.sun{position:absolute;width:clamp(120px,26vmin,240px);height:clamp(120px,26vmin,240px);top:8%;background:linear-gradient(#ffca78,#ff5386);border-radius:50%}.grid{position:absolute;inset:44% -50% -80%;transform-origin:50% 0;background-image:linear-gradient(#ef80dc88 1px,transparent 1px),linear-gradient(90deg,#ef80dc88 1px,transparent 1px);background-size:40px 40px;transform:perspective(400px) rotateX(55deg);animation:grid 2s linear infinite}@keyframes grid{to{background-position:0 40px}}',logic:'40px 격자를 상단 44% 지평선을 기준으로 perspective 400px 및 rotateX 55도로 기울인다. background-position을 한 칸씩 이동하여 지평선으로 이어지는 바닥을 만든다.',acceptance:'격자가 지평선 방향으로 좁아지는 원근과 반복 이동을 보여준다.'})
add(['accordion'],{html:'<div class="faq"><button aria-expanded="false" aria-controls="answer">어떻게 구현하나요? <span class="chevron">⌄</span></button><div id="answer" class="panel" inert><div><p>grid-template-rows를 0fr에서 1fr로 전환해 실제 내용 높이를 보간합니다. 텍스트 opacity와 화살표 회전을 함께 전환합니다.</p></div></div></div>',css:'.faq{width:85%;max-width:460px;border:1px solid #fff4;border-radius:16px;padding:20px}.faq button{display:flex;justify-content:space-between;align-items:center;width:100%;border:0;background:none;color:white;padding:10px 0;text-align:left}.chevron{transition:transform 300ms}.panel{display:grid;grid-template-rows:0fr;opacity:0;transition:grid-template-rows 300ms,opacity 300ms}.panel>div{overflow:hidden}.panel p{font-size:14px;line-height:1.7}.faq.open .panel{grid-template-rows:1fr;opacity:1}.faq.open .chevron{transform:rotate(180deg)}',js:`const button=document.querySelector('.faq button'),panel=document.querySelector('.panel');button.onclick=()=>{const open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));panel.inert=!open;document.querySelector('.faq').classList.toggle('open',open)};`,logic:'button aria-expanded와 panel inert를 함께 변경한다. grid-template-rows 0fr→1fr로 실제 내용 높이를 300ms 보간하고 opacity와 화살표 회전을 동기화한다. 닫힌 panel은 접근성/키보드에서 제외한다.',acceptance:'실제 높이와 opacity와 화살표가 함께 움직인다. Enter/Space로 toggle하고 닫힌 내용은 focus되지 않는다.'})
for(const key of ['glass-card','style-glass','spotlight-card','glow-card'])recipes[key].js=`const card=document.querySelector('article');card.addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType==='touch')return;const r=card.getBoundingClientRect();card.style.setProperty('--x',(e.clientX-r.left)+'px');card.style.setProperty('--y',(e.clientY-r.top)+'px')});`;

recipes.typewriter.css+=' .output span:after{content:"|";font-weight:300;animation:caret 800ms steps(2) infinite}@keyframes caret{50%{opacity:0}}';
recipes['gradient-text'].css=recipes['gradient-text'].css.replace('animation:color 3s linear infinite','');
recipes['gradient-text'].logic='고정된 다색 linear-gradient를 background-clip:text로 글자에만 표시한다.';
recipes['gradient-text'].acceptance='정적인 색상 변화가 글자 내부에만 나타나고 글자가 선명하다.';
recipes['shimmer-text'].css=recipes['shimmer-text'].css.replace('linear-gradient(110deg,#bba7ff,#80ddea,#fff,#c5a3ff)','linear-gradient(110deg,#65718b 35%,#fff 50%,#65718b 65%)');
recipes['shimmer-text'].logic='어두운 글자 위에 좁고 밝은 gradient band를 3초 linear로 이동시킨다.';
recipes['shimmer-text'].acceptance='다색 gradient가 아니라 밝은 빛 띠가 어두운 글자를 훑고 지나간다.';
for(const key of ['typewriter','scramble-text','number-ticker']){
 recipes[key].js=recipes[key].js!.replace('start=performance.now()};loop','start=performance.now();restart()};loop').replace('});',`return t<${key==='typewriter'?1600:key==='number-ticker'?1600:1200};});`);
}

recipes['spotlight-card']={...recipes['spotlight-card'],html:'<article tabindex="0"><small>POINTER / LIGHT</small><h1>Local<br>spotlight.</h1><p>카드 위로 포인터를 움직여 보세요</p></article>',css:'main{background:#0c1320}article{width:80%;max-width:360px;padding:28px;border:1px solid #6988aa70;border-radius:20px;background:radial-gradient(circle at var(--x,50%) var(--y,50%),#8cc5ff55,transparent 65%),#172133}h1{font-size:clamp(30px,8vw,56px)}p{font-size:12px;color:#d7e4f5}',logic:'어두운 article 내부의 pointer 좌표를 --x/--y로 저장한다. 그 좌표를 중심으로 반투명 radial-gradient를 합성하여 카드 내부만 밝힌다. 글자는 별도 DOM으로 선명하게 유지한다.'};
recipes['glow-card']={...recipes['glow-card'],html:'<article tabindex="0"><small>HOVER / FOCUS</small><h1>Glow<br>on demand.</h1><p>포인터 또는 Tab으로 빛을 켜세요</p></article>',css:'main{background:#0c1320}article{width:75%;max-width:340px;padding:28px;border:1px solid #7c76ba;border-radius:20px;background:#172133;transition:box-shadow 220ms,border-color 220ms}article:hover,article:focus-visible{border-color:#bffff3;box-shadow:0 0 18px #92f2df,0 0 60px #7b65eb}h1{font-size:clamp(30px,8vw,56px)}p{font-size:12px;color:#d7e4f5}',js:'',logic:'어두운 카드의 border와 외부 box-shadow를 hover/focus-visible 상태에서 함께 강화한다. 220ms transition을 적용하고 reduced-motion에서는 즉시 전환한다.'};
recipes['rgb-lens']={...recipes['rgb-lens'],js:recipes['rgb-lens'].js!.replaceAll('shift*.025','shift*.16'),logic:recipes['rgb-lens'].logic+' RGB Lens 변형은 색상 채널 offset 계수를 .025에서 .16으로 높여 색 분리를 더 뚜렷하게 표시한다.'};

// Canonical implementations: one renderer shared by live preview and export.
Object.assign(recipes, fidelityRecipes, batch1Recipes)
